# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys


class TestEpic1():
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_epic1US1NoEmail(self):
        self.driver.get("https://app.converge-app.net/")
        self.driver.set_window_size(1279, 1413)
        self.driver.find_element(
            By.CSS_SELECTOR, ".MuiButton-outlined > .MuiButton-label").click()
        self.driver.find_element(By.NAME, "password").send_keys("samir1234")
        self.driver.find_element(
            By.CSS_SELECTOR, ".jss143 > .MuiButton-label").click()

    def test_epic1US1InvalidEmail(self):
        self.driver.get("https://app.converge-app.net/")
        self.driver.set_window_size(1279, 1413)
        self.driver.find_element(
            By.CSS_SELECTOR, ".MuiButton-outlined > .MuiButton-label").click()
        self.driver.find_element(By.NAME, "email").send_keys("samirtester")
        self.driver.find_element(By.NAME, "password").send_keys("samir1234")
        self.driver.find_element(
            By.CSS_SELECTOR, ".jss143 > .MuiButton-label").click()
