export const bidConstants = {
  PLACE_BID_REQUEST: "BID_PLACE_REQUEST",
  PLACE_BID_SUCCESS: "BID_PLACE_SUCCESS",
  PLACE_BID_FAILURE: "BID_PLACE_FAILURE",

  GET_BY_PROJECT_REQUEST: "BID_GET_BY_PROJECT_REQUEST",
  GET_BY_PROJECT_SUCCESS: "BID_GET_BY_PROJECT_SUCCESS",
  GET_BY_PROJECT_FAILURE: "BID_GET_BY_PROJECT_FAILURE",

  CHOOSE_FREELANCER_REQUEST: "BID_CHOOSE_FREELANCER_REQUEST",
  CHOOSE_FREELANCER_SUCCESS: "BID_CHOOSE_FREELANCER_SUCCESS",
  CHOOSE_FREELANCER_FAILURE: "BID_CHOOSE_FREELANCER_FAILURE"
};
