export const collaborationConstants = {
  GET_COLLABORATION_BY_PROJECT_REQUEST: "COLLABORATION_GET_BY_PROJECT_REQUEST",
  GET_COLLABORATION_BY_PROJECT_SUCCESS: "COLLABORATION_GET_BY_PROJECT_SUCCESS",
  GET_COLLABORATION_BY_PROJECT_FAILURE: "COLLABORATION_GET_BY_PROJECT_FAILURE"
};
