export const collaborationConstants = {
  GET_COLLABORATION_BY_PROJECT_REQUEST: 'COLLABORATION_GET_BY_PROJECT_REQUEST',
  GET_COLLABORATION_BY_PROJECT_SUCCESS: 'COLLABORATION_GET_BY_PROJECT_SUCCESS',
  GET_COLLABORATION_BY_PROJECT_FAILURE: 'COLLABORATION_GET_BY_PROJECT_FAILURE',

  COLLABORATION_CREATE_REQUEST: 'COLLABORATION_CREATE_REQUEST',
  COLLABORATION_CREATE_SUCCESS: 'COLLABORATION_CREATE_SUCCESS',
  COLLABORATION_CREATE_FAILURE: 'COLLABORATION_CREATE_FAILURE',

  COLLABORATION_FILES_SUBMIT_REQUEST: 'COLLABORATION_FILES_SUBMIT_REQUEST',
  COLLABORATION_FILES_SUBMIT_SUCCESS: 'COLLABORATION_FILES_SUBMIT_SUCCESS',
  COLLABORATION_FILES_SUBMIT_FAILURE: 'COLLABORATION_FILES_SUBMIT_FAILURE',
};
