export const contactsConstants = {
  GET_CONTACTS_REQUEST: "CONTACTS_GET_REQUEST",
  GET_CONTACTS_SUCCESS: "CONTACTS_GET_SUCCESS",
  GET_CONTACTS_FAILURE: "CONTACTS_GET_FAILURE",

  SET_CURRENT_CONTACT: "CONTACTS_SET_CURRENT"
};
