export const messageConstants = {
  GET_MESSAGES_REQUEST: "GET_MESSAGES_REQUEST",
  GET_MESSAGES_SUCCESS: "GET_MESSAGES_SUCCESS",
  GET_MESSAGES_FAILURE: "GET_MESSAGES_FAILURE",

  SEND_MESSAGES_REQUEST: "SEND_MESSAGES_REQUEST",
  SEND_MESSAGES_SUCCESS: "SEND_MESSAGES_SUCCESS",
  SEND_MESSAGES_FAILURE: "SEND_MESSAGES_FAILURE"
};
