export const paymentConstants = {
  CHECK_ACCOUNT_EXISTS_REQUEST: 'PAYMENT_CHECK_ACCOUNT_EXISTS_REQUEST',
  CHECK_ACCOUNT_EXISTS_SUCCESS: 'PAYMENT_CHECK_ACCOUNT_EXISTS_SUCCESS',
  CHECK_ACCOUNT_EXISTS_FAILURE: 'PAYMENT_CHECK_ACCOUNT_EXISTS_FAILURE',
};
