export const profileConstants = {
  GET_BY_USER_REQUEST: "PROFILE_GET_BY_USER_REQUEST",
  GET_BY_USER_SUCCESS: "PROFILE_GET_BY_USER_SUCCESS",
  GET_BY_USER_FAILURE: "PROFILE_GET_BY_USER_FAILURE",

  CREATE_PROFILE_REQUEST: "PROFILE_CREATE_REQUEST",
  CREATE_PROFILE_SUCCESS: "PROFILE_CREATE_SUCCESS",
  CREATE_PROFILE_FAILURE: "PROFILE_CREATE_FAILURE",

  UPDATE_PROFILE_REQUEST: "PROFILE_UPDATE_REQUEST",
  UPDATE_PROFILE_SUCCESS: "PROFILE_UPDATE_SUCCESS",
  UPDATE_PROFILE_FAILURE: "PROFILE_UPDATE_FAILURE"
};
