export const projectConstants = {
    CREATE_PROJECT_REQUEST: 'PROJECT_CREATE_REQUEST',
    CREATE_PROJECT_SUCCESS: 'PROJECT_CREATE_SUCCESS',
    CREATE_PROJECT_FAILURE: 'PROJECT_CREATE_FAILURE',

    GET_PROJECTS_REQUEST: 'PROJECTS_GET_REQUEST',
    GET_PROJECTS_SUCCESS: 'PROJECTS_GET_SUCCESS',
    GET_PROJECTS_FAILURE: 'PROJECTS_GET_FAILURE',

    GET_PROJECT_REQUEST: 'PROJECT_GET_REQUEST',
    GET_PROJECT_SUCCESS: 'PROJECT_GET_SUCCESS',
    GET_PROJECT_FAILURE: 'PROJECT_GET_FAILURE',

}
