export const submitConstants = {
  SET_SUBMITTING: 'SUBMIT_SET',
  SHOW_MESSAGE_SUCCESS: 'SUBMIT_MESSAGE_SUCCESS',
  SHOW_MESSAGE_FAILURE: 'SUBMIT_MESSAGE_FAILURE',
  ALERT_CLEAR: 'SUBMIT_CLEAR',

  SUCCESS: 'SUCCESS',
  FAILURE: 'FAILURE',
};
