export const userConstants = {
  LOGIN_REQUEST: 'USERS_LOGIN_REQUEST',
  LOGIN_SUCCESS: 'USERS_LOGIN_SUCCESS',
  LOGIN_FAILURE: 'USERS_LOGIN_FAILURE',

  LOGOUT: 'USERS_LOGOUT',

  SIGN_UP_REQUEST: 'USERS_SIGN_UP_REQUEST',
  SIGN_UP_SUCCESS: 'USERS_SIGN_UP_SUCCESS',
  SIGN_UP_FAILURE: 'USERS_SIGN_UP_FAILURE',

  GET_ALL_REQUEST: 'USERS_GET_ALL_REQUEST',
  GET_ALL_SUCCESS: 'USERS_GET_ALL_SUCCESS',
  GET_ALL_FAILURE: 'USERS_GET_ALL_FAILURE',
};
